// BSOD.idl: BSOD.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(BSOD.tlb)。

[ uuid(db9e8877-9884-48ba-af77-a13fdb9067df), version(1.0) ]
library BSOD
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CBSODDoc 的主调度接口

	[ uuid(6032051b-2d38-4413-b773-7b33f62a30dc) ]
	dispinterface IBSOD
	{
		properties:

		methods:
	};

	//  CBSODDoc 的类信息

	[ uuid(8dc935a0-9c49-4977-8e49-9cbdc9eb0d32) ]
	coclass BSOD
	{
		[default] dispinterface IBSOD;
	};
};
